[project]
name = "esm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=3.2.0",
    "pandas>=2.2.3",
    "ruff>=0.8.4",
    "torch>=2.5.1",
]
